import test from 'node:test'
import assert from 'node:assert/strict'
import { buildDocumentPageIndex, matchFileToManifestItem, normalizeManifest, pageRecordToReference, parseManifestCsv, searchBinderPages } from './binderPageIndex.js'
const manifest = { items: [
  { vendor: 'Travis Industries / Fireplace Xtrordinair', folder: 'Travis_FPX_Lopi', priority: 'A', doc_type: 'operation_manual', title: 'FPX 864 TV 40K / 31K GSR2 Operation Manual', models: '864 TV 40K, 864 TRV 31K, GSR2', source_page: 'https://www.fireplacex.com/product/864-tv-40k-deluxe/', pdf_url: 'https://www.travisindustries.com/docs/100-01485.pdf', customer_safe: 'internal_verify_first', status: 'direct_pdf_url_found', notes: 'Use for operation details and verification.' },
  { vendor: 'Kingsman', folder: 'Kingsman', priority: 'A', doc_type: 'installation_manual', title: 'IDV34 / IDV44 Installation Manual', models: 'IDV34, IDV44, direct vent gas insert', source_page: 'https://kingsmanind.com/', pdf_url: 'https://example.com/IDV34-IDV44.pdf', customer_safe: 'internal_verify_first', status: 'direct_pdf_url_found', notes: 'Use for installer verification.' },
] }
test('normalizeManifest creates searchable document metadata', () => { const docs = normalizeManifest(manifest); assert.equal(docs.length, 2); assert.equal(docs[0].pdfFileName, '100-01485.pdf'); assert.match(docs[0].localPath, /_CURRENT_WEB_REFERENCES\/Travis_FPX_Lopi/) })
test('matchFileToManifestItem matches downloaded PDF filenames', () => { const docs = normalizeManifest(manifest); const match = matchFileToManifestItem({ name: '100-01485.pdf' }, docs); assert.equal(match.title, 'FPX 864 TV 40K / 31K GSR2 Operation Manual'); assert.equal(match.matchQuality, 'exact-file-name') })
test('buildDocumentPageIndex and searchBinderPages find exact model page hits', () => { const docs = normalizeManifest(manifest); const records = buildDocumentPageIndex({ manifestItem: docs[1], file: { name: 'IDV34-IDV44.pdf' }, pages: ['General safety information and fireplace insert labels.', 'Minimum fireplace opening dimensions for IDV34 and IDV44 direct vent gas inserts. Confirm venting and gas supply.'] }); const hits = searchBinderPages(records, 'IDV34 minimum opening'); assert.equal(hits[0].pageNumber, 2); assert.match(hits[0].snippet, /Minimum fireplace opening/i) })
test('pageRecordToReference converts page hits to drawer-safe references', () => { const docs = normalizeManifest(manifest); const [record] = buildDocumentPageIndex({ manifestItem: docs[0], file: { name: '100-01485.pdf' }, pages: ['864 TV 40K GSR2 operation instructions and warnings.'] }); const [hit] = searchBinderPages([record], '864 GSR2'); const reference = pageRecordToReference(hit); assert.equal(reference.type, 'binder-page'); assert.equal(reference.pageNumber, 1); assert.match(reference.title, /p\. 1/); assert.equal(reference.safety.customerSafe, false) })
test('parseManifestCsv supports exported manifest files', () => { const rows = parseManifestCsv('vendor,folder,title,models,pdf_url,customer_safe\nKingsman,Kingsman,IDV26 Manual,IDV26,https://example.com/idv26.pdf,internal_verify_first'); assert.equal(rows.length, 1); assert.equal(rows[0].vendor, 'Kingsman'); assert.equal(rows[0].pdfFileName, 'idv26.pdf') })
