export const proposalPlaybooks = [
  {
    id: 'fresh-quote-recap',
    name: 'Fresh Quote Recap',
    leadTemperatureFit: 'Hot',
    whenToUse: 'Recent showroom quote or quote recap where selections are still current.',
    goal: 'Recap selections and move toward approval, deposit, or the next clear step.',
    requiredReviewState: 'Reviewed quote/order source with customer, quote number, date, and totals checked.',
    customerFacingSafe: true,
    notes: 'Use when the customer is actively deciding and pricing is still fresh.',
  },
  {
    id: 'warm-follow-up',
    name: 'Warm Follow-Up',
    leadTemperatureFit: 'Warm',
    whenToUse: 'Quote sent, no decision yet, and the project still looks active.',
    goal: 'Send a helpful check-in and make the next action easy.',
    requiredReviewState: 'Reviewed quote source with current contact and project details.',
    customerFacingSafe: true,
    notes: 'Keep it helpful, not pushy.',
  },
  {
    id: 'old-quote-refresh',
    name: 'Old Quote Refresh',
    leadTemperatureFit: 'Cold',
    whenToUse: 'Older quote where pricing, availability, or project status may have changed.',
    goal: 'Reopen the door and offer a clean quote refresh.',
    requiredReviewState: 'Reviewed source plus manual confirmation that pricing may be stale.',
    customerFacingSafe: true,
    notes: 'Do not imply old pricing is still valid.',
  },
  {
    id: 'close-the-loop',
    name: 'Close the Loop',
    leadTemperatureFit: 'Cold',
    whenToUse: 'Several touches or a long quiet period with no customer response.',
    goal: 'Respectfully ask whether to keep open, refresh, or archive.',
    requiredReviewState: 'Reviewed customer and quote identity.',
    customerFacingSafe: true,
    notes: 'Low-pressure, service-minded tone.',
  },
  {
    id: 'good-better-best',
    name: 'Good / Better / Best Options',
    leadTemperatureFit: 'Warm',
    whenToUse: 'Customer is comparing routes, scopes, or budget levels.',
    goal: 'Present options clearly without overwhelming them.',
    requiredReviewState: 'Reviewed option details and totals.',
    customerFacingSafe: true,
    notes: 'Requires human-written option structure before export.',
  },
  {
    id: 'measure-needed',
    name: 'Measure Needed',
    leadTemperatureFit: 'Hot',
    whenToUse: 'Field measure or site visit is needed before final quote confidence.',
    goal: 'Explain the next step and what information is needed.',
    requiredReviewState: 'Reviewed source plus measure/install requirement confirmed.',
    customerFacingSafe: true,
    notes: 'Use when the next move is logistics, not closing.',
  },
  {
    id: 'paid-order-summary',
    name: 'Paid Order Summary',
    leadTemperatureFit: 'Closed / Paid',
    whenToUse: 'Order is paid or balance due is zero.',
    goal: 'Thank the customer and recap order/service details.',
    requiredReviewState: 'Reviewed paid/closed order source.',
    customerFacingSafe: true,
    notes: 'Never treat as a sales follow-up candidate.',
  },
  {
    id: 'internal-install-review',
    name: 'Internal Install Review',
    leadTemperatureFit: 'Needs Manual Review',
    whenToUse: 'Field measure sheets, install job sheets, photos, or handwritten support pages.',
    goal: 'Prepare internal install/support context.',
    requiredReviewState: 'Internal support source reviewed by staff.',
    customerFacingSafe: false,
    notes: 'Internal only. Do not generate customer-facing proposal from this playbook.',
  },
  {
    id: 'seasonal-fireplace-reminder',
    name: 'Seasonal Fireplace Reminder',
    leadTemperatureFit: 'Warm',
    whenToUse: 'Timing-based outreach before fireplace season or install schedules fill.',
    goal: 'Encourage the customer to plan ahead.',
    requiredReviewState: 'Reviewed customer and project fit.',
    customerFacingSafe: true,
    notes: 'Use only when timing is relevant and respectful.',
  },
  {
    id: 'showroom-revisit-invite',
    name: 'Showroom Revisit Invite',
    leadTemperatureFit: 'Warm',
    whenToUse: 'Customer may need to see options again before deciding.',
    goal: 'Invite them back into the Benson Stone showroom experience.',
    requiredReviewState: 'Reviewed customer/project context.',
    customerFacingSafe: true,
    notes: 'Good for uncertain selections or stale interest.',
  },
]
